name: Make ready package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install keystone-engine
    - name: Compile KGOs
      run: |
        python kgo_assembler.py
        python CreatePatch.py
    - name: Move contents
      run: |
        mkdir /jp/script
        mkdir -p atmosphere/contents/01002F800CB16000/romfs/
        mkdir -p atmosphere/exefs_patches/SymphonicRainENX
        mv -v New_KGO/* jp/script/
        mv -v jp atmosphere/contents/01002F800CB16000/romfs/
        mv -v song atmosphere/contents/01002F800CB16000/romfs/
        mv -v evcg atmosphere/contents/01002F800CB16000/romfs/
        mv E9A68278EDF6287D6543DE1B96A69A16.ips atmosphere/exefs_patches/SymphonicRainENX
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: atmosphere
